export {default as Title} from './Home/Title.jsx'
export {default as Banner} from './Home/Banner.jsx'
export {default as NewFits} from './Home/NewFits.jsx'
export {default as NewProduct} from './Home/NewProduct.jsx'
export {default as OldProduct} from './Home/OldProduct.jsx'
export {default as BottomMenu} from './Home/BottomMenu.jsx'
export {default as Bottom} from './Home/Bottom.jsx'
export {default as NavBar} from './Home/NavBar.jsx'