export {default as Home} from './Home.jsx'
export {default as Invest} from './Invest.jsx'
export {default as Find} from './Find.jsx'
export {default as My} from './My.jsx'
export {default as InvestDetail} from './InvestDetail.jsx'
export {default as AboutUs} from './AboutUS/AboutUs.jsx'
export {default as RiskManagement} from './RiskManagement/RiskManagement.jsx'
export {default as PlatformAdvantage} from './PlatformAdvantage/PlatformAdvantage.jsx'
